######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 19 12:28:44 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src /Users/indra/Documents/projects/development/github/Evimed-connect-cpp/src /usr/lib
LIBS += -L/Users/indra/Documents/projects/development/github/Evimed-connect-cpp/Debug -lEvimed-connect-cpp -lcurl
QT += webkit

# Input
HEADERS += src/WebkitUI.h
SOURCES += src/WebkitViewExample.cpp src/WebkitUI.cpp
