######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 19 12:28:44 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
LIBS += 
QT += webkit network

# Input
HEADERS += src/WebkitUI.h src/WebCookie.h
SOURCES += src/WebkitUI.cpp src/WebkitViewExample.cpp src/WebCookie.cpp
